---
- name: Configura meu git
  hosts: localhost
  connection: local

  tasks:
  - name: Configura 'username'
    command: git config user.name "lazarovbonifacio"
    args:
      chdir: "{{dir}}"
    
  - name: Configura 'email'
    command: git config user.email "lazarovbonifacio@outlook.com"
    args:
      chdir: "{{dir}}"
...

